app = "fagouflow"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "sh -c \"python manage.py migrate && python manage.py collectstatic --noinput\""

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "config.settings.prod"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  # REMPLACE le health check par quelque chose de plus simple
  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/"  # Au lieu de /healthz
